site_name: VaSeBuilder
repo_name: VaSeBuilder
repo_url: https://github.com/molgenis/VaSeBuilder
theme:
  name: readthedocs
extra_css:
  - 'css/custom.css'
nav:
  - 'Overview': 'index.md'
  - 'Getting started': 'getting_started.md'
  - Usage:
    - 'Running VaSeBuilder': 'usage.md'
    - Parameters:
      - 'BuildValidationSet': 'param_buildvalidationset.md'
      - 'BuildSpikeIns': 'param_buildspikeins.md'
      - 'AssembleValidationSet': 'param_assemblevalidationset.md'
      - 'Argument files': 'argfiles.md'
    - 'Contexts': 'contexts.md'
    - 'Hashing': 'hashing.md'
    - 'Filtering and Prioritization': 'filtering.md'
  - Inputs and Outputs:
    - 'Input Files': 'input_file_formats.md'
    - 'Output Files': 'output_files.md'
  - 'Q&A': 'qa.md'
